basePath: /v1
definitions:
  model.Account:
    properties:
      email:
        type: string
      email_validated:
        type: boolean
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      phone:
        type: integer
      role:
        type: integer
      status:
        type: integer
      temp:
        type: boolean
    required:
    - email
    - email_validated
    - id
    - name
    - phone
    - role
    - status
    type: object
info:
  contact:
    email: keeling.wesley@gmail.com
    name: API Support
  title: Digital ID
  version: "1.0"
paths:
  /signin:
    post:
      consumes:
      - application/json
      description: Signes in and returns a token
      parameters:
      - in: query
        name: email
        required: true
        type: string
      - in: query
        name: email_validated
        type: boolean
      - in: query
        name: id
        type: integer
      - in: query
        name: password
        required: true
        type: string
      - in: query
        name: temp
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
      summary: Signes into acocunt
      tags:
      - signin
swagger: "2.0"
