basePath: /v1
definitions:
  model.SignInResponse:
    properties:
      token:
        type: string
    type: object
info:
  contact:
    email: io.labs.development@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  title: Digital ID
  version: "1.0"
paths:
  /signin:
    post:
      consumes:
      - application/json
      description: Signes in and returns a token
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: email_validated
        type: boolean
      - in: formData
        name: id
        type: integer
      - in: formData
        name: password
        required: true
        type: string
      - in: formData
        name: temp
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SignInResponse'
      summary: Signes into acocunt
      tags:
      - signin
  /signup:
    post:
      consumes:
      - application/json
      description: Creates an account on the service
      parameters:
      - in: query
        name: email
        required: true
        type: string
      - in: query
        name: password
        required: true
        type: string
      - in: query
        name: passwordconfirm
        required: true
        type: string
      - in: query
        name: temp
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - signup
  /v1/signup/welcome/{uid}:
    post:
      consumes:
      - application/json
      description: Verifies an email with a UID sent to the account email
      parameters:
      - description: uid from email
        in: query
        name: string
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - verify
swagger: "2.0"
