basePath: /v1
definitions:
  model.SignInResponse:
    properties:
      token:
        type: string
    type: object
host: api.engin.app
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /signin:
    post:
      consumes:
      - application/json
      description: Creates an account on the service
      parameters:
      - in: query
        name: email
        required: true
        type: string
      - in: query
        name: email_validated
        type: boolean
      - in: query
        name: id
        type: integer
      - in: query
        name: password
        required: true
        type: string
      - in: query
        name: temp
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - signin
swagger: "2.0"
